---
- name: Set MLAG priority to {{ new_priority }}
  block:
    - name: Get current MLAG status for priority check
      command: nv show mlag -o json
      register: current_mlag_status
      changed_when: false

    - name: Display Priority Change
      debug:
        msg: "Current MLAG priority value is {{ (current_mlag_status.stdout | from_json).priority }}. Changing to the value {{ new_priority }}."

    - name: Configure MLAG priority
      command: nv set mlag priority {{ new_priority }}
    
    - name: Commit changes
      command: nv config apply
      register: commit_output
      failed_when: "'Aborted' in commit_output.stdout"

    - name: Wait for MLAG sync
      pause:
        seconds: 30
  when: mlag_present | default(false)
