all:
  hosts:
    leaf1:
      ansible_host: 172.30.30.221
      ansible_user: cumulus
      ansible_password: P@ssw0rd
      ansible_connection: ssh
    leaf2:
      ansible_host: 172.30.30.222
      ansible_user: cumulus
      ansible_password: P@ssw0rd
      ansible_connection: ssh
